# Simplified Jira MCP Configuration
# This replaces the complex 266-line config with a clean, minimal structure

teams:
  toolchain:
    name: "ToolChain Team"
    project: "Automotive Feature Teams"
    assigned_team: "rhivos-ft-auto-toolchain"
    members:
      - "Sameera Kalgudi"
      - "Ozan Unsal"
      - "Marcel Banas"

  assessment:
    name: "Assessment Team"
    project: "Automotive Feature Teams"
    assigned_team: "rhivos-ft-auto-assessment"
    members:
      - "Joe Simmons-Talbott"

  foa:
    name: "FoA Team"
    project: "Automotive Feature Teams"
    assigned_team: "rhivos-ft-auto-foa"
    members:
      - "Nisha Saini"
      - "Ryan Smith"

  boa:
    name: "BoA Team"
    project: "Automotive Feature Teams"
    assigned_team: "rhivos-ft-auto-boa"
    members:
      - "Jan Onderka"

organizations:
  SP:
    - "Sameera Kalgudi"
    - "Ozan Unsal"
    - "Marcel Banas"
    - "Nisha Saini"
    - "Ryan Smith"
    - "Jan Onderka"
    - "Joe Simmons-Talbott"

# Optional: User display names for better readability
user_display_names:
  rhn-support-skalgudi: "Sameera Kalgudi"
  rhn-support-ounsal: "Ozan Unsal"
  mabanas@redhat.com: "Marcel Banas"
  rhn-support-nsaini: "Nisha Saini"
  rsmit106: "Ryan Smith"
  jonderka@redhat.com: "Jan Onderka"
  rhn-support-josimmon: "Joe Simmons-Talbott" 